// lib/adPdfMerger.ts
// Post-processes Puppeteer-generated PDFs to repair named internal link destinations
// (Question <-> Explanation, Index -> Topic) and optionally merge ad PDF pages at
// regular page intervals. Preserves all ad PDF annotations (URI hyperlinks, etc.).

import { PDFDocument, PDFName, PDFDict, PDFArray, PDFRef, PDFString } from 'pdf-lib';

/**
 * Post-processes `mainPdfBuffer` to repair internal link destinations and optionally
 * insert pages from `adPdfBuffer` at every `pageInterval` pages of content.
 *
 * Internal links (`q-N`, `exp-N`, `topic-slug`) generated by Chromium use named destinations.
 * When pdf-lib copies pages (or when ad pages shift page indices), named destinations in `/Dests`
 * must be remapped to point directly to valid explicit target page references (`[ pageRef /XYZ x y z ]`).
 *
 * @param mainPdfBuffer   Buffer from Puppeteer
 * @param adPdfBuffer     Optional buffer of the uploaded advertisement PDF
 * @param pageInterval    Insert ad after every N main content pages (1–10)
 * @returns               Processed PDF as Buffer
 */
export async function processPdfWithDestinations(
  mainPdfBuffer: Buffer,
  adPdfBuffer?: Buffer | null,
  pageInterval?: number,
): Promise<Buffer> {
  const mainDoc = await PDFDocument.load(mainPdfBuffer, { ignoreEncryption: true });
  const mainPageCount = mainDoc.getPageCount();

  // 1. Build map of mainPageRef -> 0-based mainPageIndex
  const mainPages = mainDoc.getPages();
  const mainPageRefToIdx = new Map<string, number>();
  mainPages.forEach((p, idx) => {
    mainPageRefToIdx.set(p.ref.toString(), idx);
  });

  // 2. Extract named destinations dictionary (/Dests) from mainDoc catalog
  const destsRef = mainDoc.catalog.get(PDFName.of('Dests'));
  const destsDict = destsRef ? (mainDoc.context.lookup(destsRef) as PDFDict) : null;
  const namedDestsMap = new Map<string, { mainPageIndex: number; rest: any[] }>();

  if (destsDict) {
    for (const [key, val] of destsDict.entries()) {
      const destKey = key.toString().replace(/^\//, '');
      const destArray = val instanceof PDFArray ? val : (mainDoc.context.lookup(val) as PDFArray);
      if (destArray && destArray.size() > 0) {
        const targetPageRef = destArray.get(0).toString();
        const mainIdx = mainPageRefToIdx.get(targetPageRef);
        if (mainIdx !== undefined) {
          const rest: any[] = [];
          for (let k = 1; k < destArray.size(); k++) {
            rest.push(destArray.get(k));
          }
          namedDestsMap.set(destKey, { mainPageIndex: mainIdx, rest });
        }
      }
    }
  }

  // 3. Load ad document if provided
  const hasAds = !!(adPdfBuffer && pageInterval && pageInterval > 0);
  let adDoc: PDFDocument | null = null;
  let adPageIndices: number[] = [];

  if (hasAds) {
    try {
      adDoc = await PDFDocument.load(adPdfBuffer!, { ignoreEncryption: true });
      const adPageCount = adDoc.getPageCount();
      adPageIndices = Array.from({ length: adPageCount }, (_, i) => i);
    } catch (err) {
      console.error('[adPdfMerger] Failed to load ad PDF, proceeding without ads:', err);
      adDoc = null;
    }
  }

  // 4. Build output document page by page
  const resultDoc = await PDFDocument.create();
  const mainToResultPageIdx = new Map<number, number>();

  for (let i = 0; i < mainPageCount; i++) {
    const [mainPage] = await resultDoc.copyPages(mainDoc, [i]);
    resultDoc.addPage(mainPage);
    const resIdx = resultDoc.getPageCount() - 1;
    mainToResultPageIdx.set(i, resIdx);

    if (adDoc && pageInterval && pageInterval > 0) {
      const isIntervalBoundary = (i + 1) % pageInterval === 0;
      const isLastPage = i + 1 === mainPageCount;
      if (isIntervalBoundary && !isLastPage) {
        const adPagesCopied = await resultDoc.copyPages(adDoc, adPageIndices);
        for (const adPage of adPagesCopied) {
          resultDoc.addPage(adPage);
        }
      }
    }
  }

  // 5. Update /Dests dictionary in resultDoc catalog
  if (namedDestsMap.size > 0) {
    const newDestsDict = resultDoc.context.obj({});
    for (const [name, info] of namedDestsMap.entries()) {
      const newResIdx = mainToResultPageIdx.get(info.mainPageIndex);
      if (newResIdx !== undefined) {
        const targetResultPage = resultDoc.getPage(newResIdx);
        const newDestArray = resultDoc.context.obj([targetResultPage.ref, ...info.rest]);
        newDestsDict.set(PDFName.of(name), newDestArray);
      }
    }
    resultDoc.catalog.set(PDFName.of('Dests'), newDestsDict);
  }

  // 6. Update link annotations across all pages in resultDoc
  for (let i = 0; i < resultDoc.getPageCount(); i++) {
    const page = resultDoc.getPage(i);
    const annots = page.node.Annots();
    if (!annots) continue;

    for (let j = 0; j < annots.size(); j++) {
      const annotRef = annots.get(j) as PDFRef;
      const annotDict = resultDoc.context.lookup(annotRef) as PDFDict;
      if (!annotDict) continue;

      const subtype = annotDict.get(PDFName.of('Subtype'));
      if (subtype?.toString() !== '/Link') continue;

      let destVal = annotDict.get(PDFName.of('Dest'));
      let isAction = false;
      let actionDict: PDFDict | null = null;

      if (!destVal) {
        const action = annotDict.get(PDFName.of('A'));
        if (action) {
          actionDict = resultDoc.context.lookup(action) as PDFDict;
          if (actionDict) {
            destVal = actionDict.get(PDFName.of('D'));
            isAction = true;
          }
        }
      }

      if (!destVal) continue;

      let destName: string | null = null;
      if (destVal instanceof PDFName) {
        destName = destVal.toString().replace(/^\//, '');
      } else if (destVal instanceof PDFString) {
        destName = destVal.decodeText();
      }

      if (destName && namedDestsMap.has(destName)) {
        const info = namedDestsMap.get(destName)!;
        const newResIdx = mainToResultPageIdx.get(info.mainPageIndex);
        if (newResIdx !== undefined) {
          const targetPage = resultDoc.getPage(newResIdx);
          const explicitDestArray = resultDoc.context.obj([targetPage.ref, ...info.rest]);

          if (isAction && actionDict) {
            actionDict.set(PDFName.of('D'), explicitDestArray);
          } else {
            annotDict.set(PDFName.of('Dest'), explicitDestArray);
          }
        }
      }
    }
  }

  const mergedBytes = await resultDoc.save();
  return Buffer.from(mergedBytes);
}

/**
 * Legacy wrapper: inserts ad pages into `mainPdfBuffer` at `pageInterval` and repairs internal destinations.
 */
export async function mergeAdPages(
  mainPdfBuffer: Buffer,
  adPdfBuffer: Buffer,
  pageInterval: number,
): Promise<Buffer> {
  return processPdfWithDestinations(mainPdfBuffer, adPdfBuffer, pageInterval);
}

